plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - fticr_statistics_mineral.nb.html
  - fticr_statistics_organic.nb.html
  - fticr2kegg_organic.nb.html
  - fticr_viz.nb.html
